name: Python
on:
  workflow_dispatch:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Python Lint
      uses: ricardochaves/python-lint@v1.4.0
      with:
        python-root-list: "script.py"
        extra-pylint-options: "--rcfile=.pylintrc"
        use-pycodestyle: false
        use-flake8: false
        use-black: false
